### PR TITLE
Feature: Add the possibility to pass the entire configuration as a st…

### PR DESCRIPTION
**Pull request by Splaxi**
…ring paramenter

As promised, a PR that enables the user to pass the entire configuration as an argument, instead of having to work with files. We learned that Azure ACI and fileshares didn't behave as expected.

The configuration has to a json oneliner, with escaped double quotes.
```
{\"source\":{\"connection-string\":\"Server=;Initial Catalog=;Connection Timeout=300;\"},\"destination\":{\"connection-string\":\"Server=;Initial Catalog=;Connection Timeout=90;\"},\"tables\":{\"include\":[\"*\"],\"exclude\":[]},\"options\":{\"command-timeout\":1800,\"tasks\":8,\"logical-partitions\":\"auto\",\"batch-size\":100000,\"truncate-tables\":true,\"sync-identity\":false,\"safe-check\":\"readonly\",\"stop-if\":{\"secondary-indexes\":true,\"temporal-table\":true},\"retry-connection\":{\"delay-increment\":10,\"max-attempt\":5}}}
```

And to pass it correctly, it should look like this:
```
SmartBulkCopy.exe "{\"source\":{\"connection-string\":\"Server=;Initial Catalog=;Connection Timeout=300;\"},\"destination\":{\"connection-string\":\"Server=;Initial Catalog=;Connection Timeout=90;\"},\"tables\":{\"include\":[\"*\"],\"exclude\":[]},\"options\":{\"command-timeout\":1800,\"tasks\":8,\"logical-partitions\":\"auto\",\"batch-size\":100000,\"truncate-tables\":true,\"sync-identity\":false,\"safe-check\":\"readonly\",\"stop-if\":{\"secondary-indexes\":true,\"temporal-table\":true},\"retry-connection\":{\"delay-increment\":10,\"max-attempt\":5}}}"
```

The unit test simply takes the current template, persists it to disk and compares the 2 config objects, based on a json deserializer, as the objects are simple in structure.

### CODE REVIEW

**Comment by yorek** [comment]
That looks good to me, but before committing, I just want to make sure this change is really needed. With ACI you can mount a File Share where you can have the config file. Do you have already tried that road? If yes: does it work? If it work, why having the config file passed as a parameter is better?
Thanks!

**Comment by Splaxi** [comment]
We tried that, but mounting the fileshare, while there is files on it, obscures the files. I'm on mobile right now, so can't share the links that backs this up.

But if you can provide a working example, for ACI, where we can mount a File Share, and in some way get the config onto it and use it - that would awesome and then we can close this PR.

But to the best of my knowledge, it is a technical limitation in ACI, that the file share is mounted in a certain way, that hides files already present on the file share.

**Comment by yorek** [comment]
I see. I just got it working with ACI correctly, so I'll push the needed scripts so you can try them out. If everything will work as expected I'll close this PR.

**Comment by yorek** [comment]
Closing as is it has been fixed via 681de6a27f683a78d37d72fefc716719da769da0. Just use the provided script azure-deploy.sh to have it running in ACI

**Pull request closed without merging**
